spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/account}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  application.name: selfapp-account
  docker.compose.file: 'account/local/docker-compose.yml'
  jpa:
    hibernate:
      ddl-auto: update
