management:
  server.port: 8081
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - health
          - prometheus
          - metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    metrics:
      enabled: true
