version: '3.8'

services:
  account-postgres:
    image: postgres:17.4-alpine
    environment:
      - POSTGRES_DB=account
      - POSTGRES_USER=account
      - POSTGRES_PASSWORD=sElFaPP1
    ports:
      - "5432:5432"
